lexer grammar CmdCalculatorExpressionLexer;

fragment WHITESPACE_CHAR: [ \t\n\r];
TRIVIA: WHITESPACE_CHAR+;

fragment DIGIT: [0-9];
Integer: DIGIT+;
DECIMAL_POINT: '.';

SQRT_OPERATOR: 'sqrt';
GROUPING_START_BRACKET: '(';
GROUPING_END_BRACKET: ')';
ABSOLUTE_VALUE_BRACKET: '|';

ADDITION_OR_POSITIVE_OPERATOR: '+';
SUBTRACTION_OR_NEGATIVE_OPERATOR: '-';
MULTIPLICATION_OPERATOR: '*';
DIVISION_OPERATOR: '/';
EPONENTIATION_OPERATOR: '^';
NTH_ROOT_OPERATOR: '_';
MODULO_OPERATOR: '%';